"""errlore command-line interface.

Subcommands:

* ``errlore init claude-code`` -- write the two Claude Code hook scripts and
  merge them into your ``settings.json`` (one command instead of copy/edit/merge).
* ``errlore stats``   -- print aggregate memory stats for a data dir.
* ``errlore lessons`` -- list stored lessons (highest confidence first).

Everything is local and file-based; the CLI never calls the network.
"""

from __future__ import annotations

import argparse
import json
import os
import stat
import sys
from pathlib import Path
from typing import Any

from errlore import __version__

# A generated hook is a 3-line shim so the real (tested) logic stays in the
# package (errlore.integrations.claude_code). {data_dir} / {func} are filled in.
_HOOK_TEMPLATE = '''#!/usr/bin/env python3
# Generated by `errlore init claude-code`. Safe to edit; re-running init rewrites it.
import os, sys
os.environ.setdefault("ERRLORE_DATA", {data_dir!r})
from errlore.integrations.claude_code import {func}
sys.exit({func}())
'''


def _write_hook(path: Path, func: str, data_dir: str) -> None:
    path.write_text(_HOOK_TEMPLATE.format(func=func, data_dir=data_dir), encoding="utf-8")
    # Owner-only execute: the hook runs as the invoking user; group/other
    # execute bits would just widen the attack surface of a generated script.
    path.chmod((path.stat().st_mode | stat.S_IXUSR) & ~(stat.S_IXGRP | stat.S_IXOTH))


def _ensure_hook(
    hooks: dict[str, Any],
    event: str,
    command: str,
    *,
    matcher: str | None = None,
) -> bool:
    """Idempotently add a hook command to ``hooks[event]``.

    Returns True if it was added, False if an entry with the same command
    already existed (so re-running init never duplicates). ``hooks`` is
    loosely typed because it comes straight from parsed user JSON.
    """
    groups = hooks.setdefault(event, [])
    if not isinstance(groups, list):
        raise SystemExit(f"settings hooks.{event} is not a list; refusing to edit")
    for group in groups:
        if not isinstance(group, dict):
            continue
        inner = group.get("hooks")
        if not isinstance(inner, list):
            continue
        for h in inner:
            if isinstance(h, dict) and h.get("command") == command:
                return False  # already wired
    entry: dict[str, object] = {"hooks": [{"type": "command", "command": command}]}
    if matcher is not None:
        entry = {"matcher": matcher, **entry}
    groups.append(entry)
    return True


def _cmd_init_claude_code(args: argparse.Namespace) -> int:
    data_dir = os.path.abspath(os.path.expanduser(args.data_dir))
    hooks_dir = Path(os.path.expanduser(args.hooks_dir)).resolve()
    hooks_dir.mkdir(parents=True, exist_ok=True)

    post = hooks_dir / "errlore_posttooluse.py"
    failure = hooks_dir / "errlore_posttoolusefailure.py"
    session = hooks_dir / "errlore_sessionstart.py"
    _write_hook(post, "post_tool_use", data_dir)
    _write_hook(failure, "post_tool_use_failure", data_dir)
    _write_hook(session, "session_start", data_dir)

    # Same interpreter that runs the CLI -> the one where errlore is installed.
    py = sys.executable or "python3"
    cmd_post = f"{py} {post}"
    cmd_failure = f"{py} {failure}"
    cmd_session = f"{py} {session}"

    settings_path = (
        Path(".claude/settings.json").resolve()
        if args.project
        else Path(os.path.expanduser("~/.claude/settings.json"))
    )
    settings_path.parent.mkdir(parents=True, exist_ok=True)

    if settings_path.exists():
        try:
            settings = json.loads(settings_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError as exc:
            print(f"error: {settings_path} is not valid JSON ({exc});", file=sys.stderr)
            print("       left untouched.", file=sys.stderr)
            return 1
        if not isinstance(settings, dict):
            print(f"error: {settings_path} is not a JSON object; not touching it", file=sys.stderr)
            return 1
    else:
        settings = {}

    hooks = settings.setdefault("hooks", {})
    if not isinstance(hooks, dict):
        print(f"error: {settings_path} 'hooks' is not an object; not touching it", file=sys.stderr)
        return 1

    # PostToolUseFailure is where current Claude Code reports failed tool
    # calls (PostToolUse fires only on success). The PostToolUse hook stays
    # registered for older Claude Code versions.
    added_post = _ensure_hook(hooks, "PostToolUse", cmd_post, matcher="Bash")
    added_failure = _ensure_hook(hooks, "PostToolUseFailure", cmd_failure, matcher="Bash")
    added_session = _ensure_hook(hooks, "SessionStart", cmd_session)

    settings_path.write_text(json.dumps(settings, indent=2) + "\n", encoding="utf-8")

    print("errlore Claude Code hooks installed.")
    print(f"  hooks written to : {hooks_dir}")
    print(f"  memory data dir  : {data_dir}")
    print(f"  settings updated : {settings_path}")
    if not (added_post and added_failure and added_session):
        print("  (hooks were already present — nothing duplicated)")
    print("\nRestart Claude Code (or start a new session) to pick them up.")
    print("Failed Bash commands now become lessons; each new session is briefed on past pitfalls.")
    return 0


def _open_memory(data_dir: str):  # type: ignore[no-untyped-def]
    from errlore import AgentMemory

    return AgentMemory(os.path.expanduser(data_dir))


def _print_data_dir(data_dir: str) -> None:
    """Always show WHERE we read from — the #1 confusion is running `errlore
    stats` next to a quickstart ./agent_memory dir while the CLI default
    points at ~/.errlore/claude-code and silently prints zeros."""
    resolved = os.path.abspath(os.path.expanduser(data_dir))
    print(f"data dir: {resolved}  (change with --data-dir PATH)", file=sys.stderr)


def _cmd_stats(args: argparse.Namespace) -> int:
    _print_data_dir(args.data_dir)
    stats = _open_memory(args.data_dir).stats()
    if args.json:
        print(json.dumps(stats, indent=2))
        return 0
    for key in ("errors_total", "errors_resolved", "errors_unresolved",
                "lessons_total", "lessons_applied", "pending_injections"):
        if key in stats:
            print(f"{key:20} {stats[key]}")
    trust = stats.get("trust")
    if isinstance(trust, dict) and trust:
        print("trust:")
        for model, weight in sorted(trust.items(), key=lambda kv: kv[1], reverse=True):
            print(f"  {model:24} {weight:.3f}")
    return 0


def _cmd_lessons(args: argparse.Namespace) -> int:
    _print_data_dir(args.data_dir)
    lessons = _open_memory(args.data_dir).lessons(limit=args.limit)
    if not lessons:
        print("(no lessons yet)")
        return 0
    for le in lessons:
        print(f"[{le.confidence:.2f} x{le.applied_count}] {le.pattern} -> {le.solution}")
    return 0


def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="errlore",
        description="Memory for AI agents that learns from failures.",
    )
    p.add_argument("--version", action="version", version=f"errlore {__version__}")
    sub = p.add_subparsers(dest="command", required=True)

    p_init = sub.add_parser("init", help="wire errlore into a tool")
    init_sub = p_init.add_subparsers(dest="target", required=True)
    p_cc = init_sub.add_parser("claude-code", help="install Claude Code hooks + settings")
    p_cc.add_argument("--project", action="store_true",
                      help="write to ./.claude/settings.json instead of the global ~/.claude one")
    p_cc.add_argument("--data-dir", default="~/.errlore/claude-code",
                      help="where the memory lives (default: ~/.errlore/claude-code)")
    p_cc.add_argument("--hooks-dir", default="~/.errlore/hooks",
                      help="where the hook scripts are written (default: ~/.errlore/hooks)")
    p_cc.set_defaults(func=_cmd_init_claude_code)

    p_stats = sub.add_parser("stats", help="print memory stats")
    p_stats.add_argument("--data-dir", default="~/.errlore/claude-code")
    p_stats.add_argument("--json", action="store_true", help="output raw JSON")
    p_stats.set_defaults(func=_cmd_stats)

    p_lessons = sub.add_parser("lessons", help="list stored lessons")
    p_lessons.add_argument("--data-dir", default="~/.errlore/claude-code")
    p_lessons.add_argument("--limit", type=int, default=None, help="max lessons to show")
    p_lessons.set_defaults(func=_cmd_lessons)

    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return int(args.func(args))


if __name__ == "__main__":
    sys.exit(main())
